name: fuzzfarm

on:
  schedule:
    - cron: "0 2 * * *"  # daily 02:00 UTC
  workflow_dispatch:

jobs:
  fuzzfarm:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip pytest
      - name: Run Attack-LLM generator
        run: |
          mkdir -p attack_llm_runs
          python -c "
          from software.attack_llm.src.lib import AttackLLMSimulator
          import json, datetime, random, pathlib
          sim = AttackLLMSimulator()
          data = sim.generate_with_severity(50)
          path = pathlib.Path('attack_llm_runs')/f'run_{datetime.datetime.utcnow().strftime(\"%Y%m%dT%H%M%SZ\")}.json'
          path.write_text(json.dumps(data, indent=2))
          print(f'Attack-LLM batch saved to {path}')
          "
      - name: Generate all NT vectors
        run: |
          for s in security_tests/novel_vectors/nt*_*.py; do python "$s"; done
      - name: Generate NT-02 vector
        run: |
          python security_tests/novel_vectors/nt02_ethical_drift.py
      - name: Check critical exploits
        run: |
          python security_tests/fuzzfarm/collector.py 